- name: Install mysql
  ansible.builtin.apt:
    name: mysql-server
    #mysql-server is a package name
    state: present
    update_cache: yes

- name: Start service mysql
  ansible.builtin.service:
    name: mysql
    #linux command 'systemctl start mysql'
    state: started    
    enabled: yes

- name: Install PyMySQL
  ansible.builtin.apt:
    name: python3-pymysql
    # package name
    state: present    

- name: Create a new database 
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock  
    #enable login for ansible aka passworless login as root user  

- name: Create database user and all database privileges
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present   
    login_unix_socket: /run/mysqld/mysqld.sock  
    #enable login for ansible 